FROM python:3.12

# Install Java (for Spark)
RUN apt-get update && apt-get install -y wget \
    && wget https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20+8/OpenJDK11U-jdk_x64_linux_hotspot_11.0.20_8.tar.gz \
    && mkdir -p /usr/lib/jvm/ \
    && tar -xzf OpenJDK11U-jdk_x64_linux_hotspot_11.0.20_8.tar.gz -C /usr/lib/jvm/ \
    && rm OpenJDK11U-jdk_x64_linux_hotspot_11.0.20_8.tar.gz

ENV JAVA_HOME="/usr/lib/jvm/jdk-11.0.20+8"
ENV PATH="$JAVA_HOME/bin:$PATH"

# Install dependencies
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt


# Download required Spark Kafka package
RUN mkdir -p /opt/spark/jars && \
    wget -P /opt/spark/jars/ \
    https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar && \
    wget -P /opt/spark/jars/ \
    https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.5.0/kafka-clients-3.5.0.jar


# Copy the consumer script
COPY consumer.py .

# Run the consumer
CMD ["python", "consumer.py"]
